auto: true

name: Translate House
description: Expertise in community localization
latest_version: 0.0
author: Translate House

about_url: http://translatehouse.org/about.html
gh_url: https://github.com/translate
